#!/bin/bash  
#SBATCH --job-name="Region_07"  
#SBATCH --output="Region_07_offload.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 00:02:00

module load intel/2015.2.164
module load mvapich2_ib

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @offloadall /oasis/scratch/comet/rbarnes1/temp_project/srtm_region/Region_07.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/Region_07-%n.tif

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/