#!/bin/bash  
#SBATCH --job-name="Region_06"  
#SBATCH --output="Region_06_retain.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --overcommit
#SBATCH --export=ALL  
#SBATCH -t 00:10:00

module load intel/2015.2.164
module load mvapich2_ib

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun /home/rbarnes1/dist_pf/parallel_pit_fill.exe many @retainall /oasis/scratch/comet/rbarnes1/temp_project/srtm_region/Region_06.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/Region_06-%n.tif