#!/bin/bash  
#SBATCH --job-name="Region_04"  
#SBATCH --output="Region_04_cache.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 00:02:00

module load intel/2015.2.164
module load mvapich2_ib

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/

mpirun /home/rbarnes1/dist_pf/parallel_pit_fill.exe many /scratch/$USER/$SLURM_JOBID/temp-%n /oasis/scratch/comet/rbarnes1/temp_project/srtm_region/Region_04.layout /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/Region_04-%n.tif

find /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/ -delete ; mkdir /oasis/scratch/comet/rbarnes1/temp_project/srtm_output/
rm -rf /scratch/$USER/$SLURM_JOBID/temp-%n*