#!/bin/bash  
#SBATCH --job-name="pamap_pas"  
#SBATCH --output="pamap_pas.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 48:00:00

gMPI=mpirun
gEXE=/home/rbarnes1/temp/parallel_d8_accum.exe
gLAYOUTNAME=layout.layout
gONEMANY=many
gEVICT=@evict
gDATASET=pamap_pas
gLAYER=d8
gOUTLAYER=accum
gTEMPDIR=/oasis/scratch/comet/rbarnes1/temp_project/temp/$gDATASET
gCORES=48

echo "###############"
echo "#FULL DATASET"
echo "###############"

. ../generic_job.sh

gEVICT=$gTEMPDIR

. ../generic_job.sh

gEVICT=@evict


echo "###############"
echo "#STRONG SCALING"
echo "###############"

gLAYOUTNAME=pas-44.layout


gCORES=48 
. ../generic_job.sh

gCORES=33 
. ../generic_job.sh

gCORES=17 
. ../generic_job.sh

gCORES=9  
. ../generic_job.sh

gCORES=5  
. ../generic_job.sh

gCORES=3  
. ../generic_job.sh

gCORES=2  
. ../generic_job.sh


echo "###############"
echo "WEAK SCALING"
echo "###############"


gCORES=45 
gLAYOUTNAME=pas-44.layout
. ../generic_job.sh

gCORES=33 
gLAYOUTNAME=pas-32.layout
. ../generic_job.sh

gCORES=24 
gLAYOUTNAME=pas-23.layout
. ../generic_job.sh

gCORES=17 
gLAYOUTNAME=pas-16.layout
. ../generic_job.sh

gCORES=9  
gLAYOUTNAME=pas-8.layout 
. ../generic_job.sh

gCORES=5  
gLAYOUTNAME=pas-4.layout 
. ../generic_job.sh

gCORES=3  
gLAYOUTNAME=pas-2.layout 
. ../generic_job.sh

gCORES=2  
gLAYOUTNAME=pas-1.layout 
. ../generic_job.sh
