#!/bin/bash  
#SBATCH --job-name="srtm_g"  
#SBATCH --output="srtm_g.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 48:00:00

module load boost/1.55.0
module load intel/2015.2.164
module load mvapich2_ib

rm -rf   /oasis/scratch/comet/rbarnes1/temp_project/temp/srtm_g
mkdir -p /oasis/scratch/comet/rbarnes1/temp_project/temp/srtm_g
rm -rf   /oasis/scratch/comet/rbarnes1/temp_project/output/srtm_g
mkdir -p /oasis/scratch/comet/rbarnes1/temp_project/output/srtm_g

/home/rbarnes1/temp/parallel_flats.exe /oasis/scratch/comet/rbarnes1/temp_project/srtm_global/filled/srtm_global.layout                     500  /oasis/scratch/comet/rbarnes1/temp_project/temp/srtm_g/sg-%f.tif  /oasis/scratch/comet/rbarnes1/temp_project/output/srtm_g/%f-d8.tif noflip