#!/bin/bash  
#SBATCH --job-name="srtm_gr"  
#SBATCH --output="srtm_gr.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 48:00:00

module load boost/1.55.0
module load intel/2015.2.164
module load mvapich2_ib

rm -rf   /oasis/scratch/comet/rbarnes1/temp_project/temp/srtm_gr
mkdir -p /oasis/scratch/comet/rbarnes1/temp_project/temp/srtm_gr
rm -rf   /oasis/scratch/comet/rbarnes1/temp_project/output/srtm_gr
mkdir -p /oasis/scratch/comet/rbarnes1/temp_project/output/srtm_gr

/home/rbarnes1/temp/parallel_flats.exe /oasis/scratch/comet/rbarnes1/temp_project/srtm_global_resampled/filled/srtm_global_resampled.layout 150  /scratch/$USER/$SLURM_JOBID/sgr-%f.tif /oasis/scratch/comet/rbarnes1/temp_project/output/srtm_gr/%f-d8.tif noflip