#!/bin/bash  
#SBATCH --job-name="srtm_global_resample"  
#SBATCH --output="srtm_global_resample.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 08:00:00

#Deflation times and sizes of N44W094 by algorithm
#
#    Algorithm  Time  Size
#    Deflate     20s   46M
#    LZW         16s  101M
#    LZMA       388s   46M
#    None         4s  223M
#
#Therefore, we use the Deflate algorithm for its balance of speed and efficacy

cd /oasis/scratch/comet/rbarnes1/temp_project/srtm_global

#The regex in this expression selects both the input files and the output files.
#The output filenams are recrafted to look like the input lines. Finally, the
#list is sorted and only the unique elements passed on. This effectively allows
#the process to restart if it is interrupted, provided possibly corrupted files
#are removed per the comment below.
find . -maxdepth 1 -regex '\(.*hgt\|.*hgt.tif\)' | sed 's/.tif//' | sort | uniq -u | xargs -t -n 1 -P 12 -I {} gdalwarp -co 'COMPRESS=DEFLATE' -ts 10803 10803 -ot Int16 {} {}.tif