#!/bin/bash  
#SBATCH --job-name="pamap_pan"  
#SBATCH --output="pamap_pan.%j.%N.out"  
#SBATCH --partition=compute  
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=24  
#SBATCH --export=ALL  
#SBATCH -t 09:00:00

gMPI=mpirun
gEXE=/home/rbarnes1/temp/parallel_d8_accum.exe
gLAYOUTNAME=layout.layout
gONEMANY=many
gEVICT=@evict
gDATASET=pamap_pan
gLAYER=d8
gOUTLAYER=accum
gTEMPDIR=/oasis/scratch/comet/rbarnes1/temp_project/temp/$gDATASET
gCORES=48

echo "###############"
echo "#FULL DATASET"
echo "###############"

. ../generic_job.sh

gEVICT=$gTEMPDIR

. ../generic_job.sh


echo "###############"
echo "#STRONG SCALING"
echo "###############"

gLAYOUTNAME=pan-44.layout


gCORES=48 
. ../generic_job.sh

gCORES=33 
. ../generic_job.sh

gCORES=17 
. ../generic_job.sh

gCORES=9 
. ../generic_job.sh

gCORES=5 
. ../generic_job.sh

gCORES=3 
. ../generic_job.sh

gCORES=2 
. ../generic_job.sh


echo "###############"
echo "WEAK SCALING"
echo "###############"


gCORES=45 
gLAYOUTNAME=pan-44.layout
. ../generic_job.sh

gCORES=33 
gLAYOUTNAME=pan-32.layout
. ../generic_job.sh

gCORES=24 
gLAYOUTNAME=pan-23.layout
. ../generic_job.sh

gCORES=17 
gLAYOUTNAME=pan-16.layout
. ../generic_job.sh

gCORES=9  
gLAYOUTNAME=pan-8.layout
. ../generic_job.sh

gCORES=5  
gLAYOUTNAME=pan-4.layout
. ../generic_job.sh

gCORES=3  
gLAYOUTNAME=pan-2.layout
. ../generic_job.sh

gCORES=2  
gLAYOUTNAME=pan-1.layout
. ../generic_job.sh
